# configs/promise12_unet.yaml

# Defaults that apply to all commands unless overridden
defaults:
  arch: unet
  device: cpu
  num_workers: 2
  resize: 128
  threshold: 0.5
  save_dir: ./runs/promise12_unet/
  dataset: promise12

# Train-specific settings
train:
  train_split: train
  val_split: val
  download: true
  pretrained: true
  epochs: 10
  batch_size: 16
  lr: 0.001
  track_val_dice: true
  weight_decay: 0.0
  bce_weight: 1.0
  dice_weight: 1.0
  boundary_weight: 0.0
  # checkpoint: ./runs/promise12_unet/best.pt

# Evaluate-specific settings
evaluate:
  split: val
  checkpoint: ./runs/promise12_unet/best.pt
  metrics: [dice, confusion, pr]
  threshold: 0.5
  save_metrics: ./runs/promise12_unet/best.metrics

# Visualize-specific settings
visualize:
  split: val
  checkpoint: ./runs/promise12_unet/best.pt
  val_dice_path: ./runs/promise12_unet/val_dice_over_epochs.npy
  fig_save_dir: ./runs/promise12_unet/figs/
  visualizations: [preds, val_dice_vs_epoch, bland_altman]

